# Command completion for transkribe
# Generated by Clikt

## Options for transkribe
complete -c transkribe -l generate-completion
complete -c transkribe -l author -s a -r -d 'Specify author to restrict search to'
complete -c transkribe -l branch -s b -r -d 'Specify branch to restrict search to (unset: all branches, "$remote/$branch" to include fetches)'
complete -c transkribe -l week-day -s w -r -d 'Specify weekday range to limit search to'
complete -c transkribe -l depth -s m -r -d 'Specify the depth of recursive directory search'
complete -c transkribe -l force-recursion -s F -r -d 'Force recursion up to speficied depth'
complete -c transkribe -l symbolic-links -s L -d 'Toggle inclusion of symbolic links in recursive directory search'
complete -c transkribe -s d -l days -r -d 'Specify the number of days back to include'
complete -c transkribe -s u -l until -r -d 'Specify the number of days back until this day'
complete -c transkribe -s D -l date-format -r -d 'Specify the number of days back until this day'
complete -c transkribe -s h -l help -d 'Display this help screen'
complete -c transkribe -s g -l gpg-signed -d 'Show if commit is GPG signed (G) or not (N)'
complete -c transkribe -s f -l fetch -l no-fetch -d 'Fetch the latest commits beforehand'
complete -c transkribe -s s -l silence -d 'Silences the no activity message (useful when running in a directory having many repositories)'
complete -c transkribe -s r -l report -d 'Generate a file with the report'
complete -c transkribe -s c -l diff-stat -r -d 'Show diffstat for every matched commit'
complete -c transkribe -s A -l after -r -d 'List commits after this date'
complete -c transkribe -s B -l before -r -d 'List commits before this date'
complete -c transkribe -s R -l author-date -d 'Display the author date instead of the committer date'
complete -c transkribe -l verbose -d 'verbose'
complete -c transkribe -l quote -d 'GET via HTTP a random quote from Game of Thrones'

